# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: OTSTask@3
    inputs:
      OTSService: 'DevOps TestHub'
      teamspace: 'Initial Team Space'
      project: 'Project2'
      branch: 'master'
      repo: 'https://github.com/Preethi-AS/server-action.git'
      filePath: 'Proj30/4WebUITests.xml'
      exportReport: 'C:/TAMLog/exportReport.xml'

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'C:/TAMLog/exportReport.xml'
      searchFolder: 'C:/TAMLog'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: 'SBD SAP Tests'



