trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'
  # name: 'MySystemAgent'

steps:
- script: |
    NODE_DEBUG=tls,https node test-tls.js
    node test-tls.js
  displayName: 'Node.js TLS debug log'
  