trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: OTSTask@3
    inputs:
      OTSService: 'Sofy-DTHub-Connection'
      teamspace: 'Initial Team Space'
      project: 'SBD SAP Tests'
      branch: 'main'
      repo: 'https://github.com/virtualmonster/SBD.git'
      filePath: 'google/google homepage.dtx.yaml'



