trigger:
  - azure-pipelines

pool:
  name: 'Default'
  variables:
  NODE_OPTIONS: "--tls-min-v1.2"


steps:
  - task: OTSTask@3
    inputs:
      OTSService: 'DTHub-1104'
      teamspace: 'Initial Team Space'
      project: 'ProjectTest'
      branch: 'master'
      repo: 'https://github.com/Preethi-AS/server-action.git'
      filePath: 'Proj30/4WebUITests.xml'


