trigger:
  - azure-pipelines

pool:
  name: 'Default'
  vmImage: ubuntu-latest  
  variables:NODE_EXTRA_CA_CERTS: 'C:\AzureAgent\_work\6\s\ca-master-hcl.crt'


steps:
  - script: |
      curl --tlsv1.2 --cacert $(Build.SourcesDirectory)\ca-master-hcl.crt https://master-hcl.tp-k8s.nonprod.hclpnp.com/test/
    displayName: 'Test with TLS 1.2 and custom CA'

  - task: OTSTask@3
    inputs:
      OTSService: 'DevOpsTestHub'
      teamspace: 'Initial Team Space'
      project: 'Project2'
      branch: 'master'
      repo: 'https://github.com/Preethi-AS/server-action.git'
      filePath: 'Proj30/4WebUITests.xml'


