trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: OTSTask@3
    inputs:
      OTSService: 'DTHubConn'
      teamspace: 'Initial Team Space'
      project: 'Project2'
      branch: 'main'
      repo: 'https://github.com/Preethi-AS/DTHub.git'
      filePath: 'google/google homepage.dtx.yaml'



