trigger:
  - azure-pipelines

pool:
  name: 'Default'

steps:
  - task: OTSTask@3
    inputs:
      OTSService: 'DevOpsTestHub'
      teamspace: 'Initial Team Space'
      project: 'Project2'
      branch: 'master'
      repo: 'https://github.com/Preethi-AS/server-action.git'
      filePath: 'Proj30/4WebUITests.xml'


