trigger:
  - azure-pipelines 

pool:
  name: 'Default'
  vmImage: ubuntu-latest

steps:
  - script: |
      curl --tlsv1.2 --insecure -v https://master-hcl.tp-k8s.nonprod.hclpnp.com/test
    displayName: "Curl with revocation check disabled (Ubuntu)"

  - task: OTSTask@3
    inputs:
      OTSService: 'DevOpsTestHub'
      teamspace: 'Initial Team Space'
      project: 'Project2'
      branch: 'master'
      repo: 'https://github.com/Preethi-AS/server-action.git'
      filePath: 'Proj30/4WebUITests.xml'

