trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: RTASTask@3
    inputs:
      OTSService: '1105-server-connection'
      teamspace: 'Initial Team Space'
      project: 'Project2'
      branch: 'master'
      repo: 'https://github.com/Preethi-AS/server-action.git'
      filePath: 'Proj30/4WebUITests.xml'
      exportReport: 'C:/TAMLog/exportReport.xml'

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'C:/TAMLog/exportReport.xml'
