trigger:
  - main

pool:
  #vmImage: ubuntu-latest
  name: 'MySystemAgent'

steps:
  - task: OTSTask@3
    displayName: 'Run OTS Tests'
    inputs:
      OTSService: 'SofyServer1'
      teamspace: 'Initial Team Space'
      project: 'Project1'
      branch: 'main'
      repo: 'https://github01.hclpnp.com/preethi-as/separator-master.git'
      filePath: 'Amazon/test3.dtx.yaml'
