trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: OTSTask@3
    inputs:
      OTSService: 'Sofy-DTHub-Connection'
      teamspace: 'Initial Team Space'
      project: 'SBD SAP Tests'
      branch: 'master'
      repo: 'https://github.com/Preethi-AS/server-action.git'
      filePath: 'SAP_GUI/SAPTest.testsuite'



