trigger:
  - azure-pipelines

pool:
  name: 'Default'
  vmImage: ubuntu-latest

steps:
  - script: |
      curl --ssl-no-revoke --cacert $(Build.SourcesDirectory)\ca-master-hcl.crt https://master-hcl.tp-k8s.nonprod.hclpnp.com/test
    displayName: 'Test with custom CA'

  - task: OTSTask@3
    inputs:
      OTSService: 'DevOpsTestHub'
      teamspace: 'Initial Team Space'
      project: 'Project2'
      branch: 'master'
      repo: 'https://github.com/Preethi-AS/server-action.git'
      filePath: 'Proj30/4WebUITests.xml'


