trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: OTSTask@3
    inputs:
      OTSService: 'Sofy-DTHub-Connection'
      teamspace: 'Initial Team Space'
      project: 'ProjectTest'
      branch: 'main'
      repo: 'https://github.com/anandnd/CodeSweep-Example.git'
      filePath: 'cs-sample/src/.codesweep'
      exportReport: '$(Agent.TempDirectory)/exportReport.xml'

  - script: |
      if [ -f "$(Agent.TempDirectory)/exportReport.xml" ]; then
        echo "✅ exportReport.xml was generated."
      else
        echo "❌ exportReport.xml was NOT generated."
        exit 1
      fi
    displayName: 'Check if exportReport.xml Exists'

  - script: cat "$(Agent.TempDirectory)/exportReport.xml"
    displayName: 'Display exportReport.xml Contents'

  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Agent.TempDirectory)/exportReport.xml'
      searchFolder: '$(Agent.TempDirectory)'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: 'SBD SAP Tests'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish exportReport.xml as Artifact'
    inputs:
      PathtoPublish: '$(Agent.TempDirectory)/exportReport.xml'
      ArtifactName: 'TestReport'
      publishLocation: 'Container'
