trigger:
  - main

pool:
  vmImage: ubuntu-latest
  #name: 'Default'

steps:
  - task: OTSTask@3
    displayName: 'Run OTS Tests'
    inputs:
      OTSService: 'MasterConSofy'
      teamspace: 'Initial Team Space'
      project: 'Emerald_Demo'
      branch: 'main'
      repo: 'https://github.com/oresteegidio/EmeraldDemo'
      filePath: 'Emerald-UI-Tests/Bath_Search.testsuite'
      exportReport: '$(Agent.TempDirectory)/exportReport.xml'
  - script: |
      if [ -f "$(Agent.TempDirectory)/exportReport.xml" ]; then
        echo "✅ exportReport.xml was generated."
      else
        echo "❌ exportReport.xml was NOT generated."
        exit 1
      fi
    displayName: 'Check if exportReport.xml Exists'

  - script: cat "$(Agent.TempDirectory)/exportReport.xml"
    displayName: 'Display exportReport.xml Contents'

  - task: PublishTestResults@2
    displayName: 'Publish JUnit Test Results'
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '$(Agent.TempDirectory)/exportReport.xml'
      searchFolder: '$(Agent.TempDirectory)'
      mergeTestResults: true
      failTaskOnFailedTests: true
      testRunTitle: 'SBD Test'
