trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: OTSTask@3
    inputs:
      OTSService: 'Sofy-DTHub-Connection'
      teamspace: 'Initial Team Space'
      project: 'ProjectTest'
      branch: 'main'
      repo: 'https://github.com/anandnd/CodeSweep-Example.git'
      filePath: 'cs-sample/src/.codesweep'
      exportReport: '$(Agent.TempDirectory)/exportReport.xml'
    
  - task: PublishTestResults@2
    condition: always()
    inputs:
     testResultsFormat: 'JUnit'
     testResultsFiles: '$(Agent.TempDirectory)/exportReport.xml'
     searchFolder: '$(Agent.TempDirectory)'
     mergeTestResults: true
     failTaskOnFailedTests: true
     testRunTitle: 'SBD SAP Tests'



