trigger:
main

pool:
  vmImage: ubuntu-latest

steps:
task: OTSTask@3
  inputs:
    OTSService: 'DevOps TestHub'
    teamspace: 'Initial Team Space'
    project: 'Project2'
    branch: 'master'
    repo: 'https://github.com/Preethi-AS/server-action.git'
    filePath: 'Proj30/4WebUITests.xml'
    exportReport: '$(Agent.TempDirectory)/exportReport.xml'
task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Agent.TempDirectory)/exportReport.xml'
    searchFolder: '$(Agent.TempDirectory)'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'SBD SAP Tests'
